// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm8ilaPsakP5a4NXzPpc7icuumr2TXD68',
    appId: '1:345740076484:web:317c77a24f7d20fdc07091',
    messagingSenderId: '345740076484',
    projectId: 'my-health-33d03',
    authDomain: 'my-health-33d03.firebaseapp.com',
    storageBucket: 'my-health-33d03.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1WS8FEFCfhD0EiTVDViTdh8AuLefJVws',
    appId: '1:345740076484:android:43b4691d5a425b9ac07091',
    messagingSenderId: '345740076484',
    projectId: 'my-health-33d03',
    storageBucket: 'my-health-33d03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcS2Hg5W4z_rWfiT67-r2dktqH2sghY3s',
    appId: '1:345740076484:ios:60e8b66e4cff41e8c07091',
    messagingSenderId: '345740076484',
    projectId: 'my-health-33d03',
    storageBucket: 'my-health-33d03.appspot.com',
    iosBundleId: 'com.example.myHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcS2Hg5W4z_rWfiT67-r2dktqH2sghY3s',
    appId: '1:345740076484:ios:60e8b66e4cff41e8c07091',
    messagingSenderId: '345740076484',
    projectId: 'my-health-33d03',
    storageBucket: 'my-health-33d03.appspot.com',
    iosBundleId: 'com.example.myHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm8ilaPsakP5a4NXzPpc7icuumr2TXD68',
    appId: '1:345740076484:web:12f15383d8828357c07091',
    messagingSenderId: '345740076484',
    projectId: 'my-health-33d03',
    authDomain: 'my-health-33d03.firebaseapp.com',
    storageBucket: 'my-health-33d03.appspot.com',
  );
}
